name: dating_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  geolocator: ^5.1.5
  latlong: ^0.6.1
  flutter_bloc: ^2.0.1
  equatable: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true