name: flutter_exam_app_tdd
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dartz: ^0.8.9
  http: ^0.12.0+2
  flutter_bloc: ^2.1.1
  equatable: ^1.0.1
  geolocator: ^5.1.5
  latlong: ^0.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^2.2.2

flutter:
  uses-material-design: true